# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
#
#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence 
# whose values do not exceed four million, find the sum of the even-valued terms.
#
# Brutforce method


require "benchmark"

def measure
  time = Benchmark.measure do
    yield
  end
  puts time
end

measure do
  def fib_less(value)
    prev = 0
    curr = 1
    sum = 0

    begin
#      puts "PREV: " + prev.to_s + " CURR: " + curr.to_s
      temp = curr
      sum += curr if curr % 2 == 0
      curr += prev
      prev = temp

    end  while prev < value
    return sum
  end 

  puts fib_less(4000000)
end